services:
  - type: web
    name: bullseye-api
    env: docker
    plan: free
    buildCommand: docker build -t bullseye-api .
    startCommand: docker run -p $PORT:$PORT -e PORT=$PORT -e TF_CPP_MIN_LOG_LEVEL=2 -e TF_FORCE_GPU_ALLOW_GROWTH=false -e TF_MEMORY_ALLOCATION=0.8 bullseye-api
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 8000
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: false
      - key: TF_MEMORY_ALLOCATION
        value: 0.8
