services:
  - type: web
    name: bullseye-api-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bullseye_api:app --host 0.0.0.0 --port $PORT --workers 1
    buildpacks:
      - python
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 8000
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: false
      - key: TF_MEMORY_ALLOCATION
        value: 0.2
      - key: TF_CPP_VMODULE
        value: "tensorflow=0"
      - key: OMP_NUM_THREADS
        value: 1
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: RENDER_ENVIRONMENT
        value: "python"
