services:
  - type: web
    name: bullseye-api
    env: docker
    plan: free
    buildCommand: docker build -t bullseye-api .
    startCommand: docker run -p $PORT:8000 -e PORT=$PORT bullseye-api
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 8000
