applications:
  - name: bullseye-api-v3
    type: web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    # Use $PORT environment variable set by Render
    startCommand: uvicorn bullseye_api:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      # PORT is automatically set by Render, don't override it
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: false
      - key: TF_MEMORY_ALLOCATION
        value: 0.2
      - key: TF_CPP_VMODULE
        value: "tensorflow=0"
      - key: OMP_NUM_THREADS
        value: 1
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: TF_ENABLE_MKL_NATIVE_FORMAT
        value: "0"
      - key: TF_ENABLE_CPU_OPTIMIZATION
        value: "0"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
