applications:
  - name: bullseye-api-v3
    type: web
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn bullseye_api:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: PORT
        value: 8000
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: false
      - key: TF_MEMORY_ALLOCATION
        value: 0.3
      - key: TF_CPP_VMODULE
        value: "tensorflow=0"
      - key: OMP_NUM_THREADS
        value: 1
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
