services:
  - type: web
    name: bullseye-api-v2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bullseye_api:app --host 0.0.0.0 --port $PORT
    buildpacks:
      - python
