# Render Cloud deployment configuration for Bullseye API
# Optimized for 2GB RAM, 1 CPU plan

services:
  - type: web
    name: bullseye-api
    env: python
    plan: starter  # 2GB RAM, 1 CPU
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements_optimized.txt
      pip install psutil memory-profiler
    startCommand: python bullseye_api.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 3
      - key: OMP_NUM_THREADS
        value: 1
      - key: TF_MEMORY_ALLOCATION
        value: 0.5
      - key: TF_DISABLE_MKL
        value: 1
      - key: TF_DISABLE_POOL_ALLOCATOR
        value: 1
    healthCheckPath: /healthz
    autoDeploy: true
    region: oregon  # Choose closest region
    scaling:
      minInstances: 1
      maxInstances: 1  # Single instance for 2GB RAM
    disk:
      name: bullseye-storage
      mountPath: /opt/render/project/models
      sizeGB: 1  # Minimal storage for model files