applications:
  - name: bullseye-api-v3
    type: web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bullseye_api:app --host 0.0.0.0 --port 8000
